### PR TITLE
Now LocalDate,LocalDateTime,Instant are available.

### PR DESCRIPTION
**Pull request by vspkponse**
Original was the decompiled version from v1.7 .class .I fixed some of the differences. Tell me or edit it if the github .java original version is necessary.

### CODE REVIEW

**Comment by vspkponse** [comment]
Check failed？ I have test it in IntelliJ IDEA and my web project is ok.... where is the mistake?

**Comment by PascalSchumacher** [comment]
Thanks for the pull request.

DBUtils currently still requires only java 6, but you are using classes which were introduced in java 8. Therefore the builds on java 6/7 fail because these classes can not be found. See e.g.: https://travis-ci.org/apache/commons-dbutils/jobs/287860481 for details.

**Comment by vspkponse** [comment]
Ok....

**Comment by PascalSchumacher** [comment]
A possible solution for this problem would be to use reflection instead.

**Comment by vspkponse** [comment]
Will you update another new version based on java8/9 and add some new functions some day?

**Comment by PascalSchumacher** [comment]
I'm sure we will, but as far as I know there is no concrete plan when that will happen.

**Comment by garydgregory** [comment]
We could release what we have now and the at least update to Java 7 if not 8.

**Comment by vspkponse** [comment]
Looking forwarding :)

**Pull request closed without merging**
