### PR TITLE
get generated keys from queryRunner.insertBatch

### PR DESCRIPTION
**Pull request by visruth**
This class will be useful to get generated keys from the queryRunner.insertBatch operation.

Eg:-
```
   ResultSetHandler<List<Long>> rsh = new ScalarListHandler<Long>();
   Object[][] params = {{"col1row1", "col2row1"}, {"col1row2", "col2row2"}};
   List<Long> ids = queryRunner.insertBatch("INSERT INTO testtable (col1, col2) VALUES (?,?)", rsh, params);
```
Here, the `ids` object contains the generated keys of inserted rows in the order of insertion.

### CODE REVIEW

**Comment by thecarlhall** [comment]
Hi @visruth, what using the `ColumnListHandler` class?  These seem the same to me.  Can you highlight what I'm missing?

```
ColumnListHandler<Long> rsh = new ColumnListHandler<Long>();
...
```

**Comment by visruth** [comment]
Hi @thecarlhall, `queryRunner.insertBatch` doesn't support `ColumnListHandler`. How can I get generated keys (primary key) of batch insert with `ColumnListHandler`?
If you look in to the sample code I have given you can see that `ids` contain the generated keys of inserted rows in the same order of `params` rows inserted.

For multiple rows insertion in to same table I'm using batch insert in my project which reduces a lot of time compared to individual insert operation.

**Comment by thecarlhall** [comment]
Hi @visruth, I created a [project to show how this can be done](https://github.com/thecarlhall/dbutils-pr7test). There's a [test class that uses ColumnListHandler](https://github.com/thecarlhall/dbutils-pr7test/blob/master/src/test/java/org/apache/commons/dbutils/PR7Test.java) to get the IDs generated by an H2 in-memory database. Please let me know if this meets need, or if I'm missing something.

**Comment by visruth** [comment]
Hi @thecarlhall, It's my mistake, `queryRunner.insertBatch` does support `ColumnListHandler` that also achieves the same goal. Yes, it meets my need.
When I first got this requirement I made a lot of research to find if there is any existing class available to achieve the same but didn't find any so I implemented `ScalarListHandler` its name can be easily guessed by the developer because there is already a class named `ScalarHandler` which returns only one value.
Thanks a lot @thecarlhall for notifying this.

**Comment by thecarlhall** [comment]
I'm glad to hear this works for you, @visruth!
Your PR highlights the need for more docs. I'll work to update the examples.

**Pull request closed without merging**
