### PR TITLE
Add-some-Unit-Tests

### PR DESCRIPTION
**Pull request by TheRealHaui**
I have created some Unit Tests to increase code coverage which I want to contribute.

### CODE REVIEW

**Comment by TheRealHaui** [comment]
@thecarlhall 
Would you mind merging my contributions?

**Comment by thecarlhall** [comment]
Thanks, @TheRealHaui

**Comment by thecarlhall** [comment]
I'm working to either get the project setup with Git as the primary repo or fix my svn setup.  Once one of these is working, I'll merge this PR.

**Comment by TheRealHaui** [comment]
You're welcome.

**Comment by thecarlhall** [comment]
I've merged this into the new git repo at Apache.
https://git-wip-us.apache.org/repos/asf?p=commons-dbutils.git

The master branch there will eventually mirror here.

**Pull request closed without merging**
